using Careersity.Api.Infrastructure; using Careersity.Application.ExternalLearning.Requests; using Careersity.Application.ExternalLearning.Services; using Careersity.Domain.Enums; using Microsoft.AspNetCore.Authorization; using Microsoft.AspNetCore.Mvc;
namespace Careersity.Api.Controllers;
[ApiController,Authorize(Policy=SecurityPolicies.AdministratorOnly),Route("api/admin/learning-providers"),Tags("Admin External Learning")]
public sealed class AdminLearningProvidersController(ILearningProviderService service):ControllerBase
{
 [HttpPost]public async Task<IActionResult>Create(CreateLearningProviderRequest r,CancellationToken t){var x=await service.CreateAsync(r,t);return CreatedAtAction(nameof(Get),new{id=x.Id},x);}[HttpGet]public async Task<IActionResult>List([FromQuery]int page=1,[FromQuery]int pageSize=20,[FromQuery]string?search=null,[FromQuery]ContentStatus?status=null,CancellationToken t=default)=>Ok(await service.ListAdminAsync(new(page,pageSize,search,status),t));[HttpGet("{id:guid}")]public async Task<IActionResult>Get(Guid id,CancellationToken t)=>Ok(await service.GetAdminAsync(id,t));[HttpPut("{id:guid}")]public async Task<IActionResult>Update(Guid id,UpdateLearningProviderRequest r,CancellationToken t)=>Ok(await service.UpdateAsync(id,r,t));[HttpPost("{id:guid}/publish")]public async Task<IActionResult>Publish(Guid id,CancellationToken t){await service.PublishAsync(id,t);return NoContent();}[HttpPost("{id:guid}/archive")]public async Task<IActionResult>Archive(Guid id,CancellationToken t){await service.ArchiveAsync(id,t);return NoContent();}
}
[ApiController,Authorize(Policy=SecurityPolicies.AdministratorOnly),Route("api/admin/instructors"),Tags("Admin External Learning")]
public sealed class AdminInstructorsController(IInstructorService service):ControllerBase
{
 [HttpPost]public async Task<IActionResult>Create(CreateInstructorRequest r,CancellationToken t){var x=await service.CreateAsync(r,t);return CreatedAtAction(nameof(Get),new{id=x.Id},x);}[HttpGet]public async Task<IActionResult>List([FromQuery]int page=1,[FromQuery]int pageSize=20,[FromQuery]string?search=null,[FromQuery]ContentStatus?status=null,CancellationToken t=default)=>Ok(await service.ListAdminAsync(new(page,pageSize,search,status),t));[HttpGet("{id:guid}")]public async Task<IActionResult>Get(Guid id,CancellationToken t)=>Ok(await service.GetAdminAsync(id,t));[HttpPut("{id:guid}")]public async Task<IActionResult>Update(Guid id,UpdateInstructorRequest r,CancellationToken t)=>Ok(await service.UpdateAsync(id,r,t));[HttpPut("{id:guid}/provider")]public async Task<IActionResult>Provider(Guid id,ChangeInstructorProviderRequest r,CancellationToken t)=>Ok(await service.ChangeProviderAsync(id,r,t));[HttpPost("{id:guid}/publish")]public async Task<IActionResult>Publish(Guid id,CancellationToken t){await service.PublishAsync(id,t);return NoContent();}[HttpPost("{id:guid}/archive")]public async Task<IActionResult>Archive(Guid id,CancellationToken t){await service.ArchiveAsync(id,t);return NoContent();}
}
[ApiController,Authorize(Policy=SecurityPolicies.AdministratorOnly),Route("api/admin/external-learning-resources"),Tags("Admin External Learning")]
public sealed class AdminExternalLearningResourcesController(IExternalLearningResourceService service):ControllerBase
{
 [HttpPost]public async Task<IActionResult>Create(CreateExternalLearningResourceRequest r,CancellationToken t){var x=await service.CreateAsync(r,t);return CreatedAtAction(nameof(Get),new{id=x.Id},x);}[HttpGet]public async Task<IActionResult>List([FromQuery]int page=1,[FromQuery]int pageSize=20,[FromQuery]string?search=null,[FromQuery]ContentStatus?status=null,CancellationToken t=default)=>Ok(await service.ListAdminAsync(new(page,pageSize,search,status),t));[HttpGet("{id:guid}")]public async Task<IActionResult>Get(Guid id,CancellationToken t)=>Ok(await service.GetAdminAsync(id,t));[HttpPut("{id:guid}")]public async Task<IActionResult>Update(Guid id,UpdateExternalLearningResourceRequest r,CancellationToken t)=>Ok(await service.UpdateAsync(id,r,t));[HttpPost("{id:guid}/publish")]public async Task<IActionResult>Publish(Guid id,CancellationToken t){await service.PublishAsync(id,t);return NoContent();}[HttpPost("{id:guid}/archive")]public async Task<IActionResult>Archive(Guid id,CancellationToken t){await service.ArchiveAsync(id,t);return NoContent();}[HttpPost("{id:guid}/mark-reviewed")]public async Task<IActionResult>Reviewed(Guid id,CancellationToken t){await service.MarkReviewedAsync(id,t);return NoContent();}
}
[ApiController,Authorize(Policy=SecurityPolicies.AdministratorOnly),Route("api/admin/courses/{courseId:guid}/external-resources"),Tags("Admin External Learning")]
public sealed class AdminCourseExternalResourcesController(ICourseExternalResourceService service):ControllerBase
{
 [HttpPost]public async Task<IActionResult>Assign(Guid courseId,AssignExternalResourceToCourseRequest r,CancellationToken t)=>StatusCode(201,await service.AssignAsync(courseId,r,t));[HttpGet]public async Task<IActionResult>List(Guid courseId,CancellationToken t)=>Ok(await service.ListAdminAsync(courseId,t));[HttpPut("{assignmentId:guid}")]public async Task<IActionResult>Update(Guid courseId,Guid assignmentId,UpdateCourseExternalResourceRequest r,CancellationToken t)=>Ok(await service.UpdateAsync(courseId,assignmentId,r,t));[HttpDelete("{assignmentId:guid}")]public async Task<IActionResult>Remove(Guid courseId,Guid assignmentId,CancellationToken t){await service.RemoveAsync(courseId,assignmentId,t);return NoContent();}[HttpPut("reorder")]public async Task<IActionResult>Reorder(Guid courseId,ReorderCourseExternalResourcesRequest r,CancellationToken t){await service.ReorderAsync(courseId,r,t);return NoContent();}
}
