using Careersity.Domain.Enums; using Careersity.Domain.Exceptions; using Careersity.Domain.Learning; using Careersity.Domain.LearningResources; using FluentAssertions; using Xunit;
namespace Careersity.UnitTests.Domain.Learning;
public sealed class ExternalLearningDomainTests
{
 [Fact]public void ProviderValidatesNormalizesAndIsImmutableAfterPublish(){var x=new LearningProvider("Provider"," My-Provider ",websiteUrl:"https://example.com");x.Status.Should().Be(ContentStatus.Draft);x.Slug.Should().Be("my-provider");FluentActions.Invoking(()=>new LearningProvider("P","p",websiteUrl:"ftp://example.com")).Should().Throw<ArgumentException>();x.Publish();FluentActions.Invoking(()=>x.UpdateDetails("Other","other",null,null,null)).Should().Throw<DomainException>();x.Archive();FluentActions.Invoking(x.Publish).Should().Throw<DomainException>();}
 [Fact]public void InstructorValidatesProviderUrlAndLifecycle(){FluentActions.Invoking(()=>new Instructor(Guid.Empty,"Name")).Should().Throw<ArgumentException>();FluentActions.Invoking(()=>new Instructor(Guid.NewGuid(),"Name",profileUrl:"relative")).Should().Throw<ArgumentException>();var x=new Instructor(Guid.NewGuid(),"Name");x.Publish();FluentActions.Invoking(()=>x.ChangeProvider(Guid.NewGuid())).Should().Throw<DomainException>();}
 [Fact]public void ResourceValidatesUrlDurationAndPublishedReviewPolicy(){FluentActions.Invoking(()=>new ExternalLearningResource(Guid.Empty,null,"Title",ExternalResourceType.Reading,ResourceAccessType.Free,"https://example.com")).Should().Throw<ArgumentException>();FluentActions.Invoking(()=>new ExternalLearningResource(Guid.NewGuid(),null,"Title",ExternalResourceType.Reading,ResourceAccessType.Free,"bad")).Should().Throw<ArgumentException>();FluentActions.Invoking(()=>new ExternalLearningResource(Guid.NewGuid(),null,"Title",ExternalResourceType.Reading,ResourceAccessType.Free,"https://example.com",estimatedDurationMinutes:0)).Should().Throw<ArgumentOutOfRangeException>();var x=new ExternalLearningResource(Guid.NewGuid(),null,"Title",ExternalResourceType.ExternalAssessment,ResourceAccessType.Free,"https://example.com");x.Publish();x.MarkReviewed();x.LastReviewedAtUtc.Should().NotBeNull();FluentActions.Invoking(()=>x.UpdateMetadata("Other",null,ExternalResourceType.Other,ResourceAccessType.Paid,"https://other.example",null,null)).Should().Throw<DomainException>();}
 [Fact]public void AssignmentValidatesAndUpdates(){FluentActions.Invoking(()=>new CourseExternalResource(Guid.Empty,Guid.NewGuid(),0,true)).Should().Throw<ArgumentException>();FluentActions.Invoking(()=>new CourseExternalResource(Guid.NewGuid(),Guid.NewGuid(),-1,true)).Should().Throw<ArgumentOutOfRangeException>();var x=new CourseExternalResource(Guid.NewGuid(),Guid.NewGuid(),0,true);x.Update(1,false,"Notes");x.Order.Should().Be(1);x.IsRequired.Should().BeFalse();}
 [Fact]public void ResourceProgressStartAndCompletionAreIdempotent(){var enrollment=new CareerEnrollment(Guid.NewGuid(),Guid.NewGuid(),Guid.NewGuid());var course=enrollment.AddCourseProgress(Guid.NewGuid());var id=Guid.NewGuid();var first=course.AddExternalResourceProgress(id);course.AddExternalResourceProgress(id).Should().BeSameAs(first);first.Complete();var completed=first.CompletedAtUtc;first.Complete();first.CompletedAtUtc.Should().Be(completed);course.ExternalResourceProgressRecords.Should().ContainSingle();}
}
