using Careersity.Application.Abstractions.Persistence; using Careersity.Application.Common.Exceptions; using Careersity.Application.ExternalLearning.Dtos; using Careersity.Application.ExternalLearning.Requests; using Careersity.Domain.Enums; using Careersity.Domain.LearningResources; using Microsoft.EntityFrameworkCore;
namespace Careersity.Application.ExternalLearning.Services;
public sealed class CourseExternalResourceService(ICareersityDbContext db):ICourseExternalResourceService
{
 public async Task<CourseExternalResourceDto>AssignAsync(Guid courseId,AssignExternalResourceToCourseRequest r,CancellationToken t){await DraftCourse(courseId,t);if(!await db.ExternalLearningResources.AnyAsync(x=>x.Id==r.ExternalLearningResourceId,t))throw new NotFoundException("External resource was not found.");if(await db.CourseExternalResources.AnyAsync(x=>x.CourseId==courseId&&(x.ExternalLearningResourceId==r.ExternalLearningResourceId||x.Order==r.Order),t))throw new ConflictException("The resource or order is already assigned to this course.");var x=new CourseExternalResource(courseId,r.ExternalLearningResourceId,r.Order,r.IsRequired,r.Notes);db.CourseExternalResources.Add(x);await db.SaveChangesAsync(t);return (await ListAdminAsync(courseId,t)).Single(y=>y.AssignmentId==x.Id);}
 public async Task<CourseExternalResourceDto>UpdateAsync(Guid courseId,Guid id,UpdateCourseExternalResourceRequest r,CancellationToken t){await DraftCourse(courseId,t);var x=await Find(courseId,id,t);if(await db.CourseExternalResources.AnyAsync(y=>y.CourseId==courseId&&y.Id!=id&&y.Order==r.Order,t))throw new ConflictException("Resource order must be unique within the course.");x.Update(r.Order,r.IsRequired,r.Notes);await db.SaveChangesAsync(t);return (await ListAdminAsync(courseId,t)).Single(y=>y.AssignmentId==id);}
 public async Task RemoveAsync(Guid courseId,Guid id,CancellationToken t){await DraftCourse(courseId,t);var x=await Find(courseId,id,t);db.CourseExternalResources.Remove(x);await db.SaveChangesAsync(t);}
 public async Task ReorderAsync(Guid courseId,ReorderCourseExternalResourcesRequest r,CancellationToken t){await DraftCourse(courseId,t);var all=await db.CourseExternalResources.Where(x=>x.CourseId==courseId).ToListAsync(t);var items=r.Resources.ToList();if(items.Count!=all.Count||items.Select(x=>x.AssignmentId).ToHashSet().SetEquals(all.Select(x=>x.Id))==false||!items.Select(x=>x.Order).OrderBy(x=>x).SequenceEqual(Enumerable.Range(0,items.Count)))throw new ConflictException("The reorder request must contain every assignment once with contiguous orders.");await using var tx=await db.Database.BeginTransactionAsync(t);var temp=(all.Count==0?0:all.Max(x=>x.Order))+all.Count+1;for(var i=0;i<all.Count;i++)all[i].ChangeOrder(temp+i);await db.SaveChangesAsync(t);foreach(var item in items)all.Single(x=>x.Id==item.AssignmentId).ChangeOrder(item.Order);await db.SaveChangesAsync(t);await tx.CommitAsync(t);}
 public async Task<IReadOnlyCollection<CourseExternalResourceDto>>ListAdminAsync(Guid courseId,CancellationToken t){if(!await db.Courses.AsNoTracking().AnyAsync(x=>x.Id==courseId,t))throw new NotFoundException("Course was not found.");return await AdminQuery().Where(x=>x.CourseId==courseId).OrderBy(x=>x.Order).ToListAsync(t);}
 public async Task<IReadOnlyCollection<PublicExternalResourceDto>>ListPublishedAsync(string slug,CancellationToken t){var course=await db.Courses.AsNoTracking().SingleOrDefaultAsync(x=>x.Slug==slug.Trim().ToLower()&&x.Status==ContentStatus.Published,t)??throw new NotFoundException("Published course was not found.");return await (from a in db.CourseExternalResources.AsNoTracking() join r in db.ExternalLearningResources.AsNoTracking() on a.ExternalLearningResourceId equals r.Id join p in db.LearningProviders.AsNoTracking() on r.LearningProviderId equals p.Id join i0 in db.Instructors.AsNoTracking() on r.InstructorId equals i0.Id into ig from i in ig.DefaultIfEmpty() where a.CourseId==course.Id&&r.Status==ContentStatus.Published&&p.Status==ContentStatus.Published&&(i==null||i.Status==ContentStatus.Published) orderby a.Order select new PublicExternalResourceDto(r.Id,r.Title,r.Description,r.ResourceType,r.AccessType,r.Url,r.SourceLabel,p.Name,i==null?null:i.Name,r.EstimatedDurationMinutes,a.Order,a.IsRequired)).ToListAsync(t);}
 private IQueryable<CourseExternalResourceDto>AdminQuery()=>from a in db.CourseExternalResources.AsNoTracking() join r in db.ExternalLearningResources.AsNoTracking() on a.ExternalLearningResourceId equals r.Id join p in db.LearningProviders.AsNoTracking() on r.LearningProviderId equals p.Id join i0 in db.Instructors.AsNoTracking() on r.InstructorId equals i0.Id into ig from i in ig.DefaultIfEmpty() select new CourseExternalResourceDto(a.Id,a.CourseId,r.Id,r.Title,r.Description,r.ResourceType,r.AccessType,r.Url,p.Name,i==null?null:i.Name,a.Order,a.IsRequired,a.Notes,r.EstimatedDurationMinutes);
 private async Task DraftCourse(Guid id,CancellationToken t){var c=await db.Courses.AsNoTracking().SingleOrDefaultAsync(x=>x.Id==id,t)??throw new NotFoundException("Course was not found.");if(c.Status!=ContentStatus.Draft)throw new ConflictException("External resource assignments can only change while the course is Draft.");}
 private async Task<CourseExternalResource>Find(Guid courseId,Guid id,CancellationToken t)=>await db.CourseExternalResources.SingleOrDefaultAsync(x=>x.Id==id&&x.CourseId==courseId,t)??throw new NotFoundException("Course resource assignment was not found.");
}
