using Careersity.Application.Abstractions.Persistence; using Careersity.Application.Common.Exceptions; using Careersity.Application.Common.Models; using Careersity.Application.ExternalLearning.Dtos; using Careersity.Application.ExternalLearning.Requests; using Careersity.Domain.Enums; using Careersity.Domain.LearningResources; using Microsoft.EntityFrameworkCore;
namespace Careersity.Application.ExternalLearning.Services;
public sealed class ExternalLearningResourceService(ICareersityDbContext db):IExternalLearningResourceService
{
 public async Task<ExternalLearningResourceDetailDto>CreateAsync(CreateExternalLearningResourceRequest r,CancellationToken t){await Relations(r.LearningProviderId,r.InstructorId,t);var x=new ExternalLearningResource(r.LearningProviderId,r.InstructorId,r.Title,r.ResourceType,r.AccessType,r.Url,r.Description,r.SourceLabel,r.EstimatedDurationMinutes);db.ExternalLearningResources.Add(x);await db.SaveChangesAsync(t);return await GetAdminAsync(x.Id,t);}
 public async Task<ExternalLearningResourceDetailDto>UpdateAsync(Guid id,UpdateExternalLearningResourceRequest r,CancellationToken t){await Relations(r.LearningProviderId,r.InstructorId,t);var x=await Find(id,t);if(x.LearningProviderId!=r.LearningProviderId)x.ChangeProvider(r.LearningProviderId);x.AssignInstructor(r.InstructorId);x.UpdateMetadata(r.Title,r.Description,r.ResourceType,r.AccessType,r.Url,r.SourceLabel,r.EstimatedDurationMinutes);await db.SaveChangesAsync(t);return await GetAdminAsync(id,t);}
 public async Task PublishAsync(Guid id,CancellationToken t){var x=await Find(id,t);var p=await db.LearningProviders.AsNoTracking().SingleAsync(y=>y.Id==x.LearningProviderId,t);if(p.Status!=ContentStatus.Published)throw new ConflictException("The provider must be published first.");if(x.InstructorId.HasValue&&!await db.Instructors.AsNoTracking().AnyAsync(y=>y.Id==x.InstructorId&&y.Status==ContentStatus.Published,t))throw new ConflictException("The instructor must be published first.");x.Publish();await db.SaveChangesAsync(t);}
 public async Task ArchiveAsync(Guid id,CancellationToken t){var x=await Find(id,t);x.Archive();await db.SaveChangesAsync(t);} public async Task MarkReviewedAsync(Guid id,CancellationToken t){var x=await Find(id,t);x.MarkReviewed();await db.SaveChangesAsync(t);}
 public Task<ExternalLearningResourceDetailDto>GetAdminAsync(Guid id,CancellationToken t)=>Detail(id,false,t); public Task<ExternalLearningResourceDetailDto>GetPublishedAsync(Guid id,CancellationToken t)=>Detail(id,true,t);
 public async Task<PagedResult<ExternalLearningResourceListItemDto>>ListAdminAsync(ExternalLearningQuery r,CancellationToken t){var q=ListQuery();if(r.Status.HasValue)q=q.Where(x=>x.Status==r.Status);if(!string.IsNullOrWhiteSpace(r.Search)){var s=r.Search.Trim().ToLower();q=q.Where(x=>x.Title.ToLower().Contains(s));}var count=await q.CountAsync(t);return new(await q.OrderBy(x=>x.Title).Skip((r.ValidatedPage-1)*r.ValidatedPageSize).Take(r.ValidatedPageSize).ToListAsync(t),r.ValidatedPage,r.ValidatedPageSize,count);}
 public async Task<IReadOnlyCollection<ExternalLearningResourceListItemDto>>ListPublishedAsync(CancellationToken t)=>await ListQuery().Where(x=>x.Status==ContentStatus.Published&&db.LearningProviders.Any(p=>p.Id==x.ProviderId&&p.Status==ContentStatus.Published)&&(!x.InstructorId.HasValue||db.Instructors.Any(i=>i.Id==x.InstructorId&&i.Status==ContentStatus.Published))).OrderBy(x=>x.Title).ToListAsync(t);
 private IQueryable<ExternalLearningResourceListItemDto>ListQuery()=>from x in db.ExternalLearningResources.AsNoTracking() join p in db.LearningProviders.AsNoTracking() on x.LearningProviderId equals p.Id join i0 in db.Instructors.AsNoTracking() on x.InstructorId equals i0.Id into ig from i in ig.DefaultIfEmpty() select new ExternalLearningResourceListItemDto(x.Id,x.Title,x.ResourceType,x.AccessType,x.Url,p.Id,p.Name,x.InstructorId,i==null?null:i.Name,x.EstimatedDurationMinutes,x.LastReviewedAtUtc,x.Status);
 private async Task<ExternalLearningResourceDetailDto>Detail(Guid id,bool published,CancellationToken t){var x=await db.ExternalLearningResources.AsNoTracking().SingleOrDefaultAsync(x=>x.Id==id&&(!published||x.Status==ContentStatus.Published),t)??throw new NotFoundException("External learning resource was not found.");var p=await db.LearningProviders.AsNoTracking().SingleAsync(y=>y.Id==x.LearningProviderId,t);if(published&&p.Status!=ContentStatus.Published)throw new NotFoundException("External learning resource was not found.");InstructorDto? instructor=null;if(x.InstructorId.HasValue){var i=await db.Instructors.AsNoTracking().SingleAsync(y=>y.Id==x.InstructorId,t);if(published&&i.Status!=ContentStatus.Published)throw new NotFoundException("External learning resource was not found.");instructor=new(i.Id,i.LearningProviderId,p.Name,i.Name,i.Title,i.Biography,i.ProfileUrl,i.Status,i.CreatedAtUtc,i.UpdatedAtUtc);}return new(x.Id,x.Title,x.Description,x.ResourceType,x.AccessType,x.Url,x.SourceLabel,LearningProviderService.Map(p),instructor,x.EstimatedDurationMinutes,x.LastReviewedAtUtc,x.Status,x.CreatedAtUtc,x.UpdatedAtUtc);}
 private async Task Relations(Guid providerId,Guid? instructorId,CancellationToken t){if(!await db.LearningProviders.AnyAsync(x=>x.Id==providerId,t))throw new NotFoundException("Provider was not found.");if(instructorId.HasValue&&!await db.Instructors.AnyAsync(x=>x.Id==instructorId&&x.LearningProviderId==providerId,t))throw new ConflictException("The instructor must belong to the selected provider.");}
 private async Task<ExternalLearningResource>Find(Guid id,CancellationToken t)=>await db.ExternalLearningResources.SingleOrDefaultAsync(x=>x.Id==id,t)??throw new NotFoundException("External learning resource was not found.");
}
