using Careersity.Application.Abstractions.Persistence; using Careersity.Application.Common.Exceptions; using Careersity.Application.Common.Models; using Careersity.Application.ExternalLearning.Dtos; using Careersity.Application.ExternalLearning.Requests; using Careersity.Domain.Enums; using Careersity.Domain.LearningResources; using Microsoft.EntityFrameworkCore;
namespace Careersity.Application.ExternalLearning.Services;
public sealed class InstructorService(ICareersityDbContext db):IInstructorService
{
 public async Task<InstructorDto>CreateAsync(CreateInstructorRequest r,CancellationToken t){await Provider(r.LearningProviderId,t);var x=new Instructor(r.LearningProviderId,r.Name,r.Title,r.Biography,r.ProfileUrl);db.Instructors.Add(x);await db.SaveChangesAsync(t);return await GetAdminAsync(x.Id,t);}
 public async Task<InstructorDto>UpdateAsync(Guid id,UpdateInstructorRequest r,CancellationToken t){var x=await Find(id,t);x.UpdateDetails(r.Name,r.Title,r.Biography,r.ProfileUrl);await db.SaveChangesAsync(t);return await GetAdminAsync(id,t);}
 public async Task<InstructorDto>ChangeProviderAsync(Guid id,ChangeInstructorProviderRequest r,CancellationToken t){await Provider(r.LearningProviderId,t);var x=await Find(id,t);x.ChangeProvider(r.LearningProviderId);await db.SaveChangesAsync(t);return await GetAdminAsync(id,t);}
 public async Task PublishAsync(Guid id,CancellationToken t){var x=await Find(id,t);var p=await Provider(x.LearningProviderId,t);if(p.Status!=ContentStatus.Published)throw new ConflictException("The provider must be published first.");x.Publish();await db.SaveChangesAsync(t);} public async Task ArchiveAsync(Guid id,CancellationToken t){var x=await Find(id,t);x.Archive();await db.SaveChangesAsync(t);}
 public async Task<InstructorDto>GetAdminAsync(Guid id,CancellationToken t)=>await (from x in db.Instructors.AsNoTracking() join p in db.LearningProviders.AsNoTracking() on x.LearningProviderId equals p.Id where x.Id==id select new InstructorDto(x.Id,x.LearningProviderId,p.Name,x.Name,x.Title,x.Biography,x.ProfileUrl,x.Status,x.CreatedAtUtc,x.UpdatedAtUtc)).SingleOrDefaultAsync(t)??throw new NotFoundException("Instructor was not found.");
 public async Task<PagedResult<InstructorDto>>ListAdminAsync(ExternalLearningQuery r,CancellationToken t){var q=db.Instructors.AsNoTracking();if(r.Status.HasValue)q=q.Where(x=>x.Status==r.Status);if(!string.IsNullOrWhiteSpace(r.Search)){var s=r.Search.Trim().ToLower();q=q.Where(x=>x.Name.ToLower().Contains(s));}var count=await q.CountAsync(t);var items=await (from x in q join p in db.LearningProviders.AsNoTracking() on x.LearningProviderId equals p.Id orderby x.Name select new InstructorDto(x.Id,x.LearningProviderId,p.Name,x.Name,x.Title,x.Biography,x.ProfileUrl,x.Status,x.CreatedAtUtc,x.UpdatedAtUtc)).Skip((r.ValidatedPage-1)*r.ValidatedPageSize).Take(r.ValidatedPageSize).ToListAsync(t);return new(items,r.ValidatedPage,r.ValidatedPageSize,count);}
 public async Task<IReadOnlyCollection<InstructorDto>>ListPublishedAsync(Guid providerId,CancellationToken t){if(!await db.LearningProviders.AsNoTracking().AnyAsync(x=>x.Id==providerId&&x.Status==ContentStatus.Published,t))throw new NotFoundException("Published provider was not found.");return await (from x in db.Instructors.AsNoTracking() join p in db.LearningProviders.AsNoTracking() on x.LearningProviderId equals p.Id where x.LearningProviderId==providerId&&x.Status==ContentStatus.Published orderby x.Name select new InstructorDto(x.Id,x.LearningProviderId,p.Name,x.Name,x.Title,x.Biography,x.ProfileUrl,x.Status,x.CreatedAtUtc,x.UpdatedAtUtc)).ToListAsync(t);}
 private async Task<Instructor>Find(Guid id,CancellationToken t)=>await db.Instructors.SingleOrDefaultAsync(x=>x.Id==id,t)??throw new NotFoundException("Instructor was not found."); private async Task<LearningProvider>Provider(Guid id,CancellationToken t)=>await db.LearningProviders.SingleOrDefaultAsync(x=>x.Id==id,t)??throw new NotFoundException("Provider was not found.");
}
