using Careersity.Application.Abstractions.Authentication; using Careersity.Application.Abstractions.Persistence; using Careersity.Application.Common.Exceptions; using Careersity.Application.ExternalLearning.Dtos; using Careersity.Application.LearningProgress.Services; using Careersity.Domain.Enums; using Careersity.Domain.Learning; using Microsoft.EntityFrameworkCore;
namespace Careersity.Application.ExternalLearning.Services;
public sealed class LearnerExternalResourceProgressService(ICareersityDbContext db,ICurrentUser user,ICourseCompletionEvaluator completion):ILearnerExternalResourceProgressService
{
 public async Task<IReadOnlyCollection<LearnerExternalResourceProgressDto>>ListAsync(Guid enrollmentId,Guid courseId,CancellationToken t){var(enrollment,progress)=await Context(enrollmentId,courseId,false,t);return await Query(courseId,progress?.Id).ToListAsync(t);}
 public Task<LearnerExternalResourceProgressDto>StartAsync(Guid e,Guid c,Guid a,CancellationToken t)=>Mutate(e,c,a,false,t); public Task<LearnerExternalResourceProgressDto>CompleteAsync(Guid e,Guid c,Guid a,CancellationToken t)=>Mutate(e,c,a,true,t);
 private async Task<LearnerExternalResourceProgressDto>Mutate(Guid enrollmentId,Guid courseId,Guid assignmentId,bool completeResource,CancellationToken t){await using var tx=await db.Database.BeginTransactionAsync(t);var(enrollment,courseProgress)=await Context(enrollmentId,courseId,true,t);if(courseProgress is null)throw new ConflictException("The course must be started first.");var assignment=await db.CourseExternalResources.AsNoTracking().SingleOrDefaultAsync(x=>x.Id==assignmentId&&x.CourseId==courseId,t)??throw new NotFoundException("External resource assignment was not found.");if(!await db.ExternalLearningResources.AsNoTracking().AnyAsync(x=>x.Id==assignment.ExternalLearningResourceId&&x.Status==ContentStatus.Published,t))throw new NotFoundException("Published external resource was not found.");var p=courseProgress.ExternalResourceProgressRecords.SingleOrDefault(x=>x.CourseExternalResourceId==assignmentId);if(p is null){p=courseProgress.AddExternalResourceProgress(assignmentId);db.ExternalResourceProgressRecords.Add(p);}else p.RecordAccess();if(completeResource){p.Complete();await db.SaveChangesAsync(t);await completion.CompleteIfEligibleAsync(courseProgress,false,t);await CompleteEnrollment(enrollment,t);}await db.SaveChangesAsync(t);await tx.CommitAsync(t);return await Query(courseId,courseProgress.Id).SingleAsync(x=>x.AssignmentId==assignmentId,t);}
 private async Task<(CareerEnrollment Enrollment,CourseProgress? Progress)>Context(Guid enrollmentId,Guid courseId,bool activity,CancellationToken t){var id=UserId();var enrollment=await db.CareerEnrollments.Include(x=>x.CourseProgressRecords).ThenInclude(x=>x.LessonProgressRecords).Include(x=>x.CourseProgressRecords).ThenInclude(x=>x.ExternalResourceProgressRecords).SingleOrDefaultAsync(x=>x.Id==enrollmentId&&x.UserId==id,t)??throw new NotFoundException("Enrollment was not found.");var belongs=await db.PathwayLevelCourses.AsNoTracking().AnyAsync(x=>x.CourseId==courseId&&db.PathwayLevels.Any(l=>l.Id==x.PathwayLevelId&&l.CareerPathwayId==enrollment.CareerPathwayId),t);if(!belongs)throw new NotFoundException("Course was not found in this enrollment.");if(activity&&enrollment.Status!=EnrollmentStatus.Active)throw new ConflictException("Learning activity requires an active enrollment.");if(!await db.Courses.AsNoTracking().AnyAsync(x=>x.Id==courseId&&x.Status==ContentStatus.Published,t))throw new ConflictException("The course is not available.");return(enrollment,enrollment.CourseProgressRecords.SingleOrDefault(x=>x.CourseId==courseId));}
 private IQueryable<LearnerExternalResourceProgressDto>Query(Guid courseId,Guid? progressId)=>from a in db.CourseExternalResources.AsNoTracking() join r in db.ExternalLearningResources.AsNoTracking() on a.ExternalLearningResourceId equals r.Id join p in db.LearningProviders.AsNoTracking() on r.LearningProviderId equals p.Id join i0 in db.Instructors.AsNoTracking() on r.InstructorId equals i0.Id into ig from i in ig.DefaultIfEmpty() join ep0 in db.ExternalResourceProgressRecords.AsNoTracking().Where(x=>progressId.HasValue&&x.CourseProgressId==progressId) on a.Id equals ep0.CourseExternalResourceId into eg from ep in eg.DefaultIfEmpty() where a.CourseId==courseId&&r.Status==ContentStatus.Published orderby a.Order select new LearnerExternalResourceProgressDto(a.Id,r.Id,r.Title,r.Description,r.ResourceType,r.AccessType,r.Url,p.Name,i==null?null:i.Name,a.Order,a.IsRequired,ep!=null,ep!=null&&ep.CompletedAtUtc!=null,ep==null?null:ep.StartedAtUtc,ep==null?null:ep.CompletedAtUtc,r.EstimatedDurationMinutes);
 private async Task CompleteEnrollment(CareerEnrollment e,CancellationToken t){var required=await db.PathwayLevelCourses.AsNoTracking().Where(x=>x.IsRequired&&db.PathwayLevels.Any(l=>l.Id==x.PathwayLevelId&&l.CareerPathwayId==e.CareerPathwayId)).Select(x=>x.CourseId).Distinct().ToListAsync(t);var done=e.CourseProgressRecords.Where(x=>x.CompletedAtUtc!=null).Select(x=>x.CourseId).ToHashSet();if(required.Count>0&&required.All(done.Contains))e.Complete();}
 private Guid UserId()=>user.IsAuthenticated&&user.UserId.HasValue?user.UserId.Value:throw new UnauthorizedException();
}
