using Careersity.Application.Abstractions.Persistence; using Careersity.Application.Common.Exceptions; using Careersity.Application.CurriculumImports.Dtos; using Careersity.Application.CurriculumImports.Requests; using Careersity.Domain.Careers; using Careersity.Domain.Courses; using Careersity.Domain.LearningResources; using Careersity.Domain.Skills; using Microsoft.EntityFrameworkCore; using Microsoft.Extensions.Logging;
namespace Careersity.Application.CurriculumImports.Services;

public interface ICurriculumImportService { Task<CurriculumImportValidationDto> ValidateAsync(CurriculumImportRequest request,CancellationToken token); Task<CurriculumImportSummaryDto> ImportAsync(CurriculumImportRequest request,CancellationToken token); }
public sealed class CurriculumImportService(ICareersityDbContext db,ILogger<CurriculumImportService> logger):ICurriculumImportService
{
 public async Task<CurriculumImportValidationDto>ValidateAsync(CurriculumImportRequest r,CancellationToken t)
 {
  var e=new List<CurriculumImportIssue>();var w=new List<CurriculumImportIssue>();
  if(!string.Equals(r.Mode,"CreateOnly",StringComparison.OrdinalIgnoreCase))e.Add(new("mode","UnsupportedMode","Only CreateOnly imports are supported."));
  Limits(r,e); Duplicates(r.Skills.Select(x=>x.Slug),"skills","DuplicateSlug",e);Duplicates(r.Providers.Select(x=>x.Slug),"providers","DuplicateSlug",e);Duplicates(r.Courses.Select(x=>x.Slug),"courses","DuplicateSlug",e);
  var skills=r.Skills.Select(x=>x.Slug).ToHashSet(StringComparer.OrdinalIgnoreCase);var providers=r.Providers.Select(x=>x.Slug).ToHashSet(StringComparer.OrdinalIgnoreCase);var courses=r.Courses.Select(x=>x.Slug).ToHashSet(StringComparer.OrdinalIgnoreCase);
  for(var i=0;i<r.Courses.Count;i++){var c=r.Courses.ElementAt(i);foreach(var s in c.Skills.Where(x=>!skills.Contains(x.SkillSlug)))e.Add(new($"courses[{i}].skills","UnknownSkill",$"Skill '{s.SkillSlug}' was not declared in this import."));foreach(var x in c.ExternalResources.Where(x=>!providers.Contains(x.ProviderSlug)))e.Add(new($"courses[{i}].externalResources","UnknownProvider",$"Provider '{x.ProviderSlug}' was not declared in this import."));DuplicateOrders(c.Lessons.Select(x=>x.Order),$"courses[{i}].lessons",e);DuplicateOrders(c.ExternalResources.Select(x=>x.Order),$"courses[{i}].externalResources",e);foreach(var l in c.Lessons.Where(x=>x.ContentType==Careersity.Domain.Enums.LessonContentType.ExternalResource)){if(!Uri.TryCreate(l.ExternalResourceUrl,UriKind.Absolute,out var lu)||lu.Scheme is not("http" or "https"))e.Add(new($"courses[{i}].lessons.externalResourceUrl","InvalidUrl","External-resource lessons require an absolute HTTP or HTTPS URL."));}foreach(var x in c.ExternalResources){if(!Uri.TryCreate(x.Url,UriKind.Absolute,out var u)||u.Scheme is not("http" or "https"))e.Add(new($"courses[{i}].externalResources.url","InvalidUrl","External resource URL must be absolute HTTP or HTTPS."));w.Add(new($"courses[{i}].externalResources","ReviewRequired","External URL has not been manually reviewed."));}}
  foreach(var l in r.Pathway.Levels){DuplicateOrders(l.Courses.Select(x=>x.Order),"pathway.levels.courses",e);foreach(var c in l.Courses.Where(x=>!courses.Contains(x.CourseSlug)))e.Add(new("pathway.levels.courses.courseSlug","UnknownCourse",$"Course '{c.CourseSlug}' was not declared in this import."));}DuplicateOrders(r.Pathway.Levels.Select(x=>x.Order),"pathway.levels",e);
  var existing=new HashSet<string>(StringComparer.OrdinalIgnoreCase);if(await db.CareerCategories.AsNoTracking().AnyAsync(x=>x.Slug==r.Category.Slug.ToLower(),t))existing.Add("category.slug");if(await db.Careers.AsNoTracking().AnyAsync(x=>x.Slug==r.Career.Slug.ToLower(),t))existing.Add("career.slug");foreach(var s in await db.Skills.AsNoTracking().Where(x=>skills.Contains(x.Slug)).Select(x=>x.Slug).ToListAsync(t))existing.Add($"skills:{s}");foreach(var s in await db.LearningProviders.AsNoTracking().Where(x=>providers.Contains(x.Slug)).Select(x=>x.Slug).ToListAsync(t))existing.Add($"providers:{s}");foreach(var s in await db.Courses.AsNoTracking().Where(x=>courses.Contains(x.Slug)).Select(x=>x.Slug).ToListAsync(t))existing.Add($"courses:{s}");foreach(var x in existing)e.Add(new(x,"AlreadyExists","CreateOnly import conflicts with existing content."));
  return new(e.Count==0,e,w,Counts(r));
 }
 public async Task<CurriculumImportSummaryDto>ImportAsync(CurriculumImportRequest r,CancellationToken t)
 {
  var validation=await ValidateAsync(r,t);if(!validation.IsValid)throw new ConflictException("Curriculum import validation failed: "+string.Join("; ",validation.Errors.Select(x=>$"{x.Path}: {x.Message}")));
  await using var tx=await db.Database.BeginTransactionAsync(t);var category=new CareerCategory(r.Category.Name,r.Category.Slug,r.Category.Description);var career=new Career(category.Id,r.Career.Title,r.Career.Slug,r.Career.ShortDescription,estimatedDurationWeeks:r.Career.EstimatedDurationWeeks);var skills=r.Skills.ToDictionary(x=>x.Slug,x=>new Skill(x.Name,x.Slug,x.Category,x.Description),StringComparer.OrdinalIgnoreCase);var providers=r.Providers.ToDictionary(x=>x.Slug,x=>new LearningProvider(x.Name,x.Slug,x.Description,x.WebsiteUrl),StringComparer.OrdinalIgnoreCase);var instructors=new List<Instructor>();foreach(var x in r.Instructors??[])instructors.Add(new(providers[x.ProviderSlug].Id,x.Name,x.Title,profileUrl:x.ProfileUrl));var courses=new Dictionary<string,Course>(StringComparer.OrdinalIgnoreCase);var resources=new List<ExternalLearningResource>();var assignments=new List<CourseExternalResource>();
  foreach(var c in r.Courses){var course=new Course(c.Title,c.Slug,c.ShortDescription??$"Imported course: {c.Title}",c.Difficulty,c.EstimatedDurationMinutes);foreach(var l in c.Lessons)course.AddLesson(new(course.Id,l.Title,l.Slug,l.ContentType,l.EstimatedDurationMinutes,l.Order,summary:l.Summary,externalResourceUrl:l.ExternalResourceUrl,isRequired:l.IsRequired));foreach(var s in c.Skills)course.AssociateSkill(skills[s.SkillSlug].Id,s.ProficiencyLevel,s.IsPrimary);foreach(var x in c.ExternalResources){var instructor=instructors.FirstOrDefault(i=>i.LearningProviderId==providers[x.ProviderSlug].Id&&string.Equals(i.Name,x.InstructorName,StringComparison.OrdinalIgnoreCase));var resource=new ExternalLearningResource(providers[x.ProviderSlug].Id,instructor?.Id,x.Title,x.ResourceType,x.AccessType,x.Url,estimatedDurationMinutes:x.EstimatedDurationMinutes);resources.Add(resource);assignments.Add(new(course.Id,resource.Id,x.Order,x.IsRequired));}courses[c.Slug]=course;}
  var pathway=new CareerPathway(career.Id,r.Pathway.Name,r.Pathway.Version,r.Pathway.Description,r.Pathway.IsPrimary);foreach(var l in r.Pathway.Levels){var level=new PathwayLevel(pathway.Id,l.Name,l.Order,l.Description);foreach(var c in l.Courses)level.AddCourse(courses[c.CourseSlug].Id,c.Order,c.IsRequired);pathway.AddLevel(level);}
  db.CareerCategories.Add(category);db.Careers.Add(career);db.Skills.AddRange(skills.Values);db.LearningProviders.AddRange(providers.Values);db.Instructors.AddRange(instructors);db.Courses.AddRange(courses.Values);db.ExternalLearningResources.AddRange(resources);db.CourseExternalResources.AddRange(assignments);db.CareerPathways.Add(pathway);await db.SaveChangesAsync(t);await tx.CommitAsync(t);var id=Guid.NewGuid();logger.LogInformation("Curriculum import {ImportId} completed with {CourseCount} courses and {ResourceCount} external resources",id,courses.Count,resources.Count);return new(id,validation.Counts,category.Id,category.Slug,career.Id,career.Slug,pathway.Id);
 }
 private static CurriculumImportCounts Counts(CurriculumImportRequest r)=>new(1,1,r.Skills.Count,r.Providers.Count,r.Instructors?.Count??0,r.Courses.Sum(x=>x.ExternalResources.Count),r.Courses.Count,r.Courses.Sum(x=>x.Lessons.Count),1,r.Pathway.Levels.Count,r.Courses.Sum(x=>x.ExternalResources.Count)+r.Pathway.Levels.Sum(x=>x.Courses.Count));
 private static void Limits(CurriculumImportRequest r,List<CurriculumImportIssue>e){if(r.Skills.Count>100)e.Add(new("skills","LimitExceeded","Maximum 100 skills."));if(r.Providers.Count>100)e.Add(new("providers","LimitExceeded","Maximum 100 providers."));if((r.Instructors?.Count??0)>200)e.Add(new("instructors","LimitExceeded","Maximum 200 instructors."));if(r.Courses.Count>200)e.Add(new("courses","LimitExceeded","Maximum 200 courses."));if(r.Courses.Sum(x=>x.Lessons.Count)>2000)e.Add(new("courses.lessons","LimitExceeded","Maximum 2000 lessons."));if(r.Courses.Sum(x=>x.ExternalResources.Count)>3000)e.Add(new("courses.externalResources","LimitExceeded","Maximum 3000 external resources."));if(r.Pathway.Levels.Count>20)e.Add(new("pathway.levels","LimitExceeded","Maximum 20 levels."));if(r.Pathway.Levels.Sum(x=>x.Courses.Count)>500)e.Add(new("pathway.levels.courses","LimitExceeded","Maximum 500 course assignments."));}
 private static void Duplicates(IEnumerable<string>x,string path,string code,List<CurriculumImportIssue>e){if(x.Count()!=x.Distinct(StringComparer.OrdinalIgnoreCase).Count())e.Add(new(path,code,"Slugs must be unique within the import."));}private static void DuplicateOrders(IEnumerable<int>x,string path,List<CurriculumImportIssue>e){if(x.Count()!=x.Distinct().Count())e.Add(new(path,"DuplicateOrder","Order values must be unique."));}
}
