using Careersity.Application.Common.Exceptions; using Careersity.Application.ExternalLearning.Requests; using Careersity.Application.ExternalLearning.Services; using Careersity.Domain.Courses; using Careersity.Domain.Enums; using Careersity.Domain.Skills; using FluentAssertions; using Xunit;
using Careersity.Application.LearningProgress.Services; using Careersity.Domain.Learning;
namespace Careersity.UnitTests.Application;
public sealed class ExternalLearningServiceTests
{
 [Fact]public async Task ProviderLifecycleEnforcesSlugAndPublicFiltering(){await using var db=TestCatalogContext.Create();var s=new LearningProviderService(db);var draft=await s.CreateAsync(new("Provider","Provider",null,"https://example.com",null),default);await FluentActions.Awaiting(()=>s.CreateAsync(new("Other","provider",null,null,null),default)).Should().ThrowAsync<ConflictException>();(await s.ListPublishedAsync(default)).Should().BeEmpty();await s.PublishAsync(draft.Id,default);(await s.ListPublishedAsync(default)).Should().ContainSingle();await FluentActions.Awaiting(()=>s.UpdateAsync(draft.Id,new("Changed","changed",null,null,null),default)).Should().ThrowAsync<Careersity.Domain.Exceptions.DomainException>();}
 [Fact]public async Task InstructorAndResourcePublicationRequirePublishedRelatedContent(){await using var db=TestCatalogContext.Create();var ps=new LearningProviderService(db);var provider=await ps.CreateAsync(new("Provider","provider",null,null,null),default);var ins=new InstructorService(db);var instructor=await ins.CreateAsync(new(provider.Id,"Teacher",null,null,null),default);await FluentActions.Awaiting(()=>ins.PublishAsync(instructor.Id,default)).Should().ThrowAsync<ConflictException>();await ps.PublishAsync(provider.Id,default);await ins.PublishAsync(instructor.Id,default);var rs=new ExternalLearningResourceService(db);var resource=await rs.CreateAsync(new(provider.Id,instructor.Id,"Lecture",null,ExternalResourceType.LectureVideo,ResourceAccessType.Free,"https://example.com/video",null,30),default);await rs.PublishAsync(resource.Id,default);(await rs.ListPublishedAsync(default)).Should().ContainSingle();await rs.MarkReviewedAsync(resource.Id,default);(await rs.GetAdminAsync(resource.Id,default)).LastReviewedAtUtc.Should().NotBeNull();}
 [Fact]public async Task AssignmentRejectsDuplicateAndPublishedCourseMutation(){await using var db=TestCatalogContext.Create();var provider=new Careersity.Domain.LearningResources.LearningProvider("Provider","provider");provider.Publish();var resource=new Careersity.Domain.LearningResources.ExternalLearningResource(provider.Id,null,"Reading",ExternalResourceType.Reading,ResourceAccessType.Free,"https://example.com/read");resource.Publish();var course=new Course("Course","course","Description",CourseDifficulty.Beginner,30);var lesson=new Lesson(course.Id,"Lesson","lesson",LessonContentType.Article,10,0);course.AddLesson(lesson);db.AddRange(provider,resource,course,lesson);await db.SaveChangesAsync();var s=new CourseExternalResourceService(db);var assigned=await s.AssignAsync(course.Id,new(resource.Id,0,true,null),default);await FluentActions.Awaiting(()=>s.AssignAsync(course.Id,new(resource.Id,1,true,null),default)).Should().ThrowAsync<ConflictException>();course.Publish();await db.SaveChangesAsync();await FluentActions.Awaiting(()=>s.UpdateAsync(course.Id,assigned.AssignmentId,new(0,false,null),default)).Should().ThrowAsync<ConflictException>();}
 [Fact]public async Task RequiredPublishedResourceBlocksThenCompletesCourse(){await using var db=TestCatalogContext.Create();var provider=new Careersity.Domain.LearningResources.LearningProvider("Provider","provider");provider.Publish();var resource=new Careersity.Domain.LearningResources.ExternalLearningResource(provider.Id,null,"Resource",ExternalResourceType.ExternalAssessment,ResourceAccessType.Free,"https://example.com/test");resource.Publish();var course=new Course("Course","course","Description",CourseDifficulty.Beginner,30);var lesson=new Lesson(course.Id,"Lesson","lesson",LessonContentType.Article,10,0);course.AddLesson(lesson);var assignment=new Careersity.Domain.LearningResources.CourseExternalResource(course.Id,resource.Id,0,true);var enrollment=new CareerEnrollment(Guid.NewGuid(),Guid.NewGuid(),Guid.NewGuid());var progress=enrollment.AddCourseProgress(course.Id);progress.AddLessonProgress(lesson.Id).Complete();db.AddRange(provider,resource,course,lesson,assignment,enrollment);await db.SaveChangesAsync();var evaluator=new CourseCompletionEvaluator(db);(await evaluator.CompleteIfEligibleAsync(progress,false,default)).Should().BeFalse();progress.CompletedAtUtc.Should().BeNull();progress.AddExternalResourceProgress(assignment.Id).Complete();db.ExternalResourceProgressRecords.Add(progress.ExternalResourceProgressRecords.Single());await db.SaveChangesAsync();(await evaluator.CompleteIfEligibleAsync(progress,false,default)).Should().BeTrue();progress.CompletedAtUtc.Should().NotBeNull();db.AssessmentAttempts.Should().BeEmpty();}
}
